dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: Eu9IdOCMDNNtwjs0901xE53zsl6ExoZnGTo+8kOEy4qtZj0/PVCHPEfx3Ty9QFm5mSLVW6BVkJB4gHjZPuSKbMYrKIXwSFZcML4xYXMs7oWh2e9ulOVf8iSH/5MPj8+ib+UPcdwkJLhHXm3lIZs+PhySkIFbA045uPXVRT2Xusw=
  - secure: XCtfTIWdmyjp1ZDH9CPs7eXbOTAhfS031GWsru7rlOqPTWy0/RHL3BI5chBnn7Dh6ig34M6jQ2/4hcP/Qy+nPR9Gx44GF0jhEv3oEF5fyeSu3DsanKew3K0CIbnNRC4lEr/4qMaDkN4yLFeYCYpuvr0v2pyGpP9e+k7j3oqOmM8=
  - secure: o1E51adkfzse6ayaKkf+YPi4xMxDvj6ez1oEsI5HljhVuMbgvOYkrs3dkOSfsORBAR+a9F8bSbrOcXyBDzloj3v1G47r4LaSWFk8QTBDvn8cpAzbx1eErT6FcdzxqmeZ22xWXQhEg17mfomCvULc+ueDToXEP1GGkozp7KZyldk=
  - secure: VuUlF+SdWvjKA0jDLJWcHwaL+H/4shfLhy/1C3HulJVuAOtz7+UQvOsbo2s8tXQic25IynvnBxb366wbDHS4yPEi71oTH/KniV3rYa9jsDM/vIUsHi8X09Scwk8CyD84F7aEL3hKWnWlNFxgRN3YgjenRX9qeDGsG6fLin2i670=
addons:
  browserstack:
    username: sondo3
    access_key:
      secure: CnEtpDg7P8cueyUffaxg54Djy91gZUjGogXkv0gx9tV/WtfIRjVBbB9Vkmr2woOEnvHboout0mtYTZIIqMmCUTQuO7nNjMDHefBLCGS+5rLwmftU9+sf2/QSrGTkzFDBAqcqYLV4hH8C8XPWJ+YUYdpDdlm9ckQPcB8xEw2h5Ac=
